apiVersion: apps/v1
kind: Deployment
metadata:
  generation: 1
  labels:
    app: vac-benefits-directory
    name: "find-benefits-and-services"
    keel.sh/policy: all
    keel.sh/trigger: poll
  name: find-benefits-and-services
  namespace: default
  annotations:
    flux.weave.works/automated: "true"
    keel.sh/pollSchedule: "@every 2m"
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: vac-benefits-directory
      task: find-benefits-and-services
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: vac-benefits-directory
        task: find-benefits-and-services
        role: front-end
    spec:
      containers:
        - image: veteransaffairscanada/vac-benefits-directory:latest
          name: vac-benefits-directory
          imagePullPolicy: Always
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          env:
            - name: AIRTABLE_WRITE_KEY
              valueFrom:
                secretKeyRef:
                  name: vac-benefits-directory
                  key: airtable_write_key
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      tolerations:
        - key: "app"
          operator: "Equal"
          value: "fbas"
          effect: "NoSchedule"
status: {}
