apiVersion: apps/v1
kind: Deployment
metadata:
  generation: 1
  labels:
    app: vac-benefits-directory
  name: find-benefits-and-services
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: vac-benefits-directory
      task: find-benefits-and-services
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: vac-benefits-directory
        task: find-benefits-and-services
        role: front-end
    spec:
      containers:
        - image: veteransaffairscanada/vac-benefits-directory:v1.1.0
          name: vac-benefits-directory
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
              name: http
              hostPort: 80
              protocol: TCP
          resources:
            limits:
              cpu: 100m
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 200Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          env:
            - name: AIRTABLE_WRITE_KEY
              valueFrom:
                secretKeyRef:
                  name: vac-benefits-directory
                  key: airtable_write_key
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      tolerations:
        - key: "app"
          operator: "Equal"
          value: "fbas"
          effect: "NoSchedule"
status: {}
