version: 2.1

orbs:
  azure-aks: circleci/azure-aks@0.2.1
  kubernetes: circleci/kubernetes@0.4.0
  semantic-versioning: payfit/semantic-versioning@0.42.0

jobs:
  create-aks-deployment:
    executor: azure-aks/default
    parameters:
      cluster-name:
        description: Name of the AKS cluster
        type: string
      resource-group:
        description: Resource group that the cluster is in
        type: string
      namespace:
        description: Namespace to use
        type: string
      subscription:
        description: Subscription id
        type: string
    steps:
      - checkout
      - azure-aks/update-kubeconfig-with-credentials:
          cluster-name: << parameters.cluster-name >>
          resource-group: << parameters.resource-group >>
          install-kubectl: true
          perform-login: true
          subscription: << parameters.subscription >>

  deployment_development_docker:
    docker:
      - image: docker:17.12.1-ce-git
    steps:
      - checkout
      - setup_remote_docker

      # Build the image
      - run:
          command: |
            docker build  -t "${DOCKER_REGISTRY}/${NAMESPACE}/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_SHA1}"  --build-arg CIRCLE_SHA1="${CIRCLE_SHA1}" --build-arg SENTRY_DSN="${SENTRY_DSN}" --build-arg GA_UA="${GA_UA}" --build-arg GA_UA_CDS="${GA_UA_CDS}" --build-arg CIRCLE_PROJECT_REPONAME="${CIRCLE_PROJECT_REPONAME}" --build-arg CIRCLE_BRANCH="${CIRCLE_BRANCH}" --build-arg CIRCLE_REPOSITORY_URL="${CIRCLE_REPOSITORY_URL}" --build-arg WEBHOOK_URL="${WEBHOOK_URL}" --build-arg AIRTABLE_READ_KEY="${AIRTABLE_READ_KEY}" .
          name: "Build Image"
      # Scan the image
      - run:
          command: |
            docker run -p 5432:5432 -d --name db arminc/clair-db:latest
            docker run -p 6060:6060 --link db:postgres -d --name clair arminc/clair-local-scan:v2.0.1
            docker run -v /var/run/docker.sock:/var/run/docker.sock -d --name clair-scanner veteransaffairscanada/clair-scanner:latest tail -f /dev/null
            clair_ip=`docker exec -it clair hostname -i | grep -oE '[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+'`
            scanner_ip=`docker exec -it clair-scanner hostname -i | grep -oE '[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+'`
            docker exec -it clair-scanner clair-scanner --ip ${scanner_ip} --clair=http://${clair_ip}:6060 -t High "${DOCKER_REGISTRY}/${NAMESPACE}/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_SHA1}"
          name: "Scan image"
      # Deploy the image if passes the scan
      - run:
          command: |
            docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"

            BRANCH=${CIRCLE_BRANCH//[^a-zA-Z0-9]/-}
            IMAGE_NAME=${DOCKER_REGISTRY}/${NAMESPACE}/${CIRCLE_PROJECT_REPONAME}
            docker pull veteransaffairscanada/vac-benefits-directory:latest

            VERSION=$(git describe --abbrev=0 --tags || $BRANCH)
            docker tag veteransaffairscanada/vac-benefits-directory:latest $IMAGE_NAME:$VERSION
            docker push $IMAGE_NAME:${CIRCLE_SHA1}
            if [ "${CIRCLE_BRANCH}" == "develop" ]; then
            docker push $IMAGE_NAME:$VERSION
            fi
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
            docker push $IMAGE_NAME:$VERSION
            fi
          name: "Tag and Push Docker Image"
      - run:
          command: apt-get install curl && ~/repo/.circleci/notify_failure.sh
          name: "Report failing Development"
          when: on_fail

    working_directory: ~/repo

workflows:
  deployment_aks_lab:
    jobs:
    
      - deployment_development_docker:
          filters:
            branches:
              ignore:
                - develop
                - master
      - create-aks-deployment:
          cluster-name: ${AKS_CLUSTERNAME_DEV}
          resource-group: ${AKS_RESOURCE_GROUP}
          subscription: ${SUBSCRIPTION}
          namespace: "fbas-lab"
          filters:
            branches:
              ignore:
                - develop
                - master
      - azure-aks/update-container-image:
          cluster-name: ${AKS_CLUSTERNAME_DEV}
          resource-group: ${AKS_RESOURCE_GROUP}
          namespace: "fbas-lab"
          resource-name: ${AKS_DEPLOYMENT_LAB}
          container-image-updates: "vac-benefits-directory=${NAMESPACE}/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_SHA1}"
          record: true
          requires:
            - deployment_development_docker
          filters:
            branches:
              ignore:
                - develop
                - master
  deployment_aks_dev:
    jobs:
      - deployment_development_docker:
          filters:
            branches:
              ignore:
                - develop
                - master
      - create-aks-deployment:
          cluster-name: ${AKS_CLUSTERNAME_DEV}
          resource-group: ${AKS_RESOURCE_GROUP}
          subscription: ${SUBSCRIPTION}
          namespace: "fbas-dev"
          filters:
            branches:
              ignore:
                - develop
                - master
      - azure-aks/update-container-image:
          cluster-name: ${AKS_CLUSTERNAME_DEV}
          resource-group: ${AKS_RESOURCE_GROUP}
          namespace: "fbas-dev"
          resource-name: ${AKS_DEPLOYMENT_DEV}
          container-image-updates: "vac-benefits-directory=${NAMESPACE}/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_SHA1}"
          record: true
          requires:
            - deployment_development_docker
          filters:
            branches:
              ignore:
                - develop
                - master
  deployment_aks:
    jobs:
      - deployment_development_docker:
          filters:
            branches:
              only: master
      - create-aks-deployment:
          cluster-name: ${AKS_CLUSTERNAME}
          resource-group: ${AKS_RESOURCE_GROUP}
          namespace: "default"
          filters:
            branches:
              only: master
      - azure-aks/update-container-image:
          cluster-name: ${AKS_CLUSTERNAME}
          resource-group: ${AKS_RESOURCE_GROUP}
          namespace: "default"
          resource-name: ${AKS_DEPLOYMENT}
          container-image-updates: "vac-benefits-directory=${NAMESPACE}/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_SHA1}"
          record: true
          requires:
            - deployment_development_docker
          filters:
            branches:
              only: master
