apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: vac-benefits-directory
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: benefits-avantages.aks.cloud.veterans.gc.ca
      http:
        paths:
          - path: /
            backend:
              serviceName: find-benefits-and-services
              servicePort: http
